import { useEffect, useState } from 'react'
import { principles, services, taicoAssets } from './data/taicoData'
import './App.css'

function ImageSlot({ src, label, className = '', priority = false }) {
  const [failed, setFailed] = useState(!src)
  return <div className={`image-slot ${failed ? 'is-placeholder' : ''} ${className}`}>
    {!failed && <img src={src} alt={label} loading={priority ? 'eager' : 'lazy'} onError={() => setFailed(true)} />}
    {failed && <span>{label} / IMAGE SLOT</span>}
  </div>
}
function Arrow() { return <span className="arrow" aria-hidden="true">↗</span> }
function Nav({ open, setOpen }) {
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 80); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <header className={`nav ${scrolled ? 'is-scrolled' : ''}`}>
    <a className="wordmark" href="#top" aria-label="TAICO Events home">TAICO <span>EVENTS</span></a>
    <nav className={open ? 'nav-links is-open' : 'nav-links'} aria-label="Main navigation">
      <a href="#about" onClick={() => setOpen(false)}>About</a><a href="#services" onClick={() => setOpen(false)}>Services</a><a href="#work" onClick={() => setOpen(false)}>Work</a><a href="#contact" onClick={() => setOpen(false)}>Contact</a>
      <a className="nav-cta" href="mailto:taicoevents@gmail.com" onClick={() => setOpen(false)}>Plan your event <Arrow /></a>
    </nav>
    <button className={`menu-toggle ${open ? 'is-open' : ''}`} onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? 'Close menu' : 'Open menu'}><span /><span /></button>
  </header>
}
function Hero() {
  const [slide, setSlide] = useState(0)
  useEffect(() => { const timer = setInterval(() => setSlide((current) => (current + 1) % taicoAssets.hero.length), 6000); return () => clearInterval(timer) }, [])
  return <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Events <i /> Experiences <i /> Brand activations</p><h1>We create<br /><em>experiences</em><br />people remember.</h1><p className="hero-intro">Premium events, brand activations, celebrations and event styling — thoughtfully planned, creatively executed and built around your brand.</p><div className="hero-actions"><a className="button button-light" href="mailto:taicoevents@gmail.com">Plan your event <Arrow /></a><a className="text-link" href="#work">Explore our work <Arrow /></a></div></div><div className="hero-visual"><div className="hero-frame"><ImageSlot src={taicoAssets.hero[slide]} label={`Hero 0${slide + 1}`} priority /></div><div className="hero-index"><span>0{slide + 1}</span> / 02</div><div className="hero-stamp">Nairobi<br /><span>Kenya</span></div></div><div className="hero-footer"><span>Scroll to explore</span><span className="line" /><span>Serving clients nationwide</span></div></section>
}
function Intro() { return <section className="intro section-pad" id="about"><div className="section-kicker">01 <span>Taico Events Ltd</span></div><div className="intro-grid"><h2>More than events.<br /><em>We create experiences.</em></h2><div className="intro-body"><p>TAICO Events Ltd is a premium event and brand experience company specializing in corporate events, promotional campaigns, merchandise branding and experiential activations.</p><a className="text-link dark" href="#services">Discover what we do <Arrow /></a></div></div><ImageSlot src={taicoAssets.intro} label="Intro / Branding" className="intro-image" /></section> }
function Services() { return <section className="services section-pad" id="services"><div className="section-heading"><div className="section-kicker">02 <span>What we do</span></div><h2>Built around<br /><em>the experience.</em></h2></div><div className="service-list">{services.map((service) => <article className="service-row" key={service.number}><span className="service-number">{service.number}</span><ImageSlot src={service.image} label={service.title} /><div className="service-content"><h3>{service.title}</h3><p>{service.description}</p><span className="service-list-copy">{service.list}</span><Arrow /></div></article>)}</div></section> }
function Work() { return <section className="work" id="work"><div className="work-heading section-pad"><div className="section-kicker">03 <span>Selected work</span></div><h2>Experiences<br /><em>in every detail.</em></h2><p>From the first idea to the final guest, we make the invisible work feel effortless.</p></div><div className="work-grid"><ImageSlot src={taicoAssets.work[0]} label="Corporate events" className="work-tall" /><ImageSlot src={taicoAssets.work[1]} label="Brand activations" /><ImageSlot src={taicoAssets.work[2]} label="Branding" /><ImageSlot src={taicoAssets.work[3]} label="Social events" className="work-wide" /></div><div className="work-marquee"><span>Corporate events</span><i /> <span>Brand activations</span><i /> <span>Décor & styling</span><i /> <span>Experiences</span></div></section> }
function FeatureSection({ id, number, eyebrow, title, copy, images, reverse = false }) { return <section className={`feature section-pad ${reverse ? 'feature-reverse' : ''}`} id={id}><div className="section-kicker">{number} <span>{eyebrow}</span></div><div className="feature-layout"><div className="feature-copy"><h2>{title}</h2><p>{copy}</p><a className="text-link dark" href="#contact">Start a conversation <Arrow /></a></div><div className="feature-images"><ImageSlot src={images[0]} label={eyebrow} /><ImageSlot src={images[1]} label={`${eyebrow} detail`} /></div></div></section> }
function WhyTaico() { return <section className="why section-pad"><div className="section-kicker">07 <span>Why Taico</span></div><div className="why-heading"><h2>The details<br /><em>make the difference.</em></h2><p>Thoughtful planning. Creative clarity. Precise delivery.</p></div><div className="principles">{principles.map(([number, title, copy]) => <div className="principle" key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section> }
function Vision() { return <section className="vision section-pad"><div className="vision-block"><span className="eyebrow">Our vision</span><p>To become East Africa's most trusted event and brand experience company, known for delivering exceptional corporate events, activations and branding solutions.</p></div><div className="vision-block"><span className="eyebrow">Our mission</span><p>To create impactful brand experiences through strategic event planning, creative execution and premium branding solutions that help our clients grow their visibility and influence.</p></div></section> }
function Contact() { return <><section className="closing" id="contact"><ImageSlot src={taicoAssets.hero[1]} label="Closing image" /><div className="closing-copy"><span className="eyebrow">08 / Let's work together</span><h2>Let's create<br /><em>something</em><br />exceptional.</h2><p>Have an event, activation or brand experience in mind?</p><a className="button button-light" href="mailto:taicoevents@gmail.com">Start a conversation <Arrow /></a></div></section><footer className="footer"><div><a className="wordmark" href="#top">TAICO <span>EVENTS</span></a><p>Nairobi, Kenya</p></div><div className="footer-links"><a href="#services">Events</a><a href="#services">Activations</a><a href="#services">Branding</a><a href="#work">Experiences</a></div><div className="footer-contact"><a href="tel:+254724357484">+254 724 357 484</a><a href="mailto:taicoevents@gmail.com">taicoevents@gmail.com</a><a href="https://wa.me/254724357484">WhatsApp <Arrow /></a></div><div className="footer-bottom"><span>© 2026 TAICO EVENTS LTD</span><span><a href="https://instagram.com/taicoevents">Instagram</a> · <a href="https://facebook.com">Facebook</a> · <a href="https://tiktok.com/@taicoevents">TikTok</a></span></div></footer></> }
function App() { const [menuOpen, setMenuOpen] = useState(false); return <><Nav open={menuOpen} setOpen={setMenuOpen} /><main><Hero /><Intro /><Services /><Work /><FeatureSection id="corporate" number="04" eyebrow="Corporate events" title={<>Where business<br /><em>meets experience.</em></>} copy="Conferences, seminars, corporate dinners, galas, AGMs, product launches, awards, team building and networking — produced with purpose." images={taicoAssets.corporate} /><FeatureSection id="activations" number="05" eyebrow="Brand activations" title={<>Make your brand<br /><em>impossible to ignore.</em></>} copy="Experiential activations, promotional campaigns and branded environments built to earn attention and create real connection." images={taicoAssets.activation} reverse /><FeatureSection id="social" number="06" eyebrow="Social events" title={<>Your moment.<br /><em>Our craft.</em></>} copy="Weddings, birthdays, traditional ceremonies, showers, fundraisers, picnics and celebrations with a warmer kind of precision." images={taicoAssets.social} /><FeatureSection id="decor" number="06" eyebrow="Décor & styling" title={<>Every space<br /><em>tells a story.</em></>} copy="Luxury tents, floral arrangements, table styling, stages, backdrops and lounge setups shaped to feel unmistakably yours." images={taicoAssets.decor} reverse /><WhyTaico /><Vision /><Contact /></main></> }
export default App
